export const home = (req, res) => res.send("HOME")
export const search = (req, res) => res.send("Search")
export const videos = (req, res) => res.send("Videos")
export const upload = (req, res) => res.send("UPLOAD")
export const videoDetail = (req, res) => res.send("VIDEO_DETAIL")
export const editVideo = (req, res) => res.send("EDIT_VIDEO")
export const deleteVideo = (req, res) => res.send("DELETE_VIDEO")
